# Generated by Django 3.2.23 on 2024-01-25 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_delete_address'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='companies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='companies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
