# Generated by Django 3.2.23 on 2024-02-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
        ('profiles', '0003_remove_userprofile_invoice_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletters.newsletter'),
        ),
    ]
