# Generated by Django 3.2.23 on 2024-01-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_company_userprofile'),
        ('profiles', '0004_alter_userprofile_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='companies.company'),
        ),
    ]
