# Generated by Django 3.2.23 on 2024-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_newsletter_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
