# Generated by Django 3.2.23 on 2024-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240202_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_ref',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
