# Generated by Django 3.2.23 on 2024-02-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20240202_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
