# Generated by Django 3.2.23 on 2024-01-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('participant_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
