# Generated by Django 3.2.23 on 2024-01-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20240130_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
