# Generated by Django 3.2.23 on 2024-01-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_billing_address'),
        ('companies', '0002_alter_company_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
