# Generated by Django 3.2.23 on 2024-01-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_userprofile_companies'),
        ('companies', '0005_alter_company_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='profiles.userprofile'),
        ),
    ]
