# Generated by Django 3.2.23 on 2024-01-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('product', 'Product'), ('buy_x_get_y', 'Buy X Get Y')], default='percentage', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('buy_x_quantity', models.IntegerField(blank=True, help_text='Relevant for "Buy X Get Y" discounts. The quantity to buy (X).', null=True)),
                ('get_y_quantity', models.IntegerField(blank=True, help_text='Relevant for "Buy X Get Y" discounts. The quantity to get for free (Y).', null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='The start date of the promo code validity', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='The end date of the promo code validity', null=True)),
                ('product_discounted', models.ForeignKey(blank=True, help_text='Relevant for product-specific discounts or "Buy X Get Y" discounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounted_product', to='products.product')),
            ],
        ),
    ]
