# Generated by Django 3.2.23 on 2024-02-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
